DELETE FROM blocks WHERE project_id = 1;

INSERT INTO blocks (project_id, type, order_index, content) VALUES
(1, 'projectHeroDoubleLogo', 0, '{"bg_image":"img/progetto-1.png", "logo_left":"img/logo-onlus-1.png", "logo_right":"img/ets-logo-navbar.png"}'),
(1, 'projectIntro', 1, '{"title_thin":"Fondazione", "title_bold":"IL BULLONE", "description":"Ci sono progetti che ci ricordano perché facciamo questo mestiere.\nCollaborare con Fondazione Il Bullone è uno di questi.\nCon loro abbiamo ideato e lanciato la nuova campagna digital di raccolta fondi indirizzata alla Fondazione. Un progetto che parla di rinascita, coraggio e comunicazione come strumento di cambiamento reale."}'),
(1, 'imageGallery3', 2, '{"images":["uploads/bullone-hero.jpg", "uploads/bullone-galleria-1.jpg", "uploads/bullone-galleria-2.jpg"]}'),
(1, 'textBlock', 3, '{"title":"La penna come sibolo di rinascita", "text":"Per i giovani della Fondazione – i <strong>B.Livers</strong> – la scrittura è un atto catartico: raccontarsi diventa il primo passo per riconoscersi di nuovo come persone, e non solo come pazienti o ex malati.\n<strong>La campagna mostra \\"gli effetti\\" che una penna può avere</strong>: alleggerire, far dimenticare la malattia e restituire la voglia di mettersi in gioco.\nProtagonisti sono cinque giovani redattori del giornale Il Bullone, che con le loro parole ci invitano a un gesto concreto: abbonarsi e donare per permettere ad altri ragazzi di intraprendere lo stesso percorso.\n\\"Abbiamo scelto di raccontare la leggerezza ritrovata\\", spiega Sergio Muller, Chief Communication Officer di A-Tono. \\"Cinque giovani e una penna, che diventa protagonista di piccoli momenti in cui si riscoprono come individui e non più solo come malati.\\""}'),
(1, 'textBlock', 4, '{"title":"Una strategia digital-first per amplificare il valore", "text":"La campagna è stata pensata con un <strong>approccio digital-first</strong>, ottimizzando ogni euro investito per massimizzare impatto e conversione. La strategia media e i contenuti sono stati progettati per parlare alle persone giuste, nel modo più empatico, diretto e sostenibile possibile.\n\\"La collaborazione con A-Tono ETS ci permette di amplificare la voce dei nostri ragazzi e il valore del nostro modello\\", afferma Bill Niada, fondatore e presidente di Fondazione Il Bullone. \\"Crediamo che questa campagna, potente nella sua autenticità e mirata nella strategia digital, ci aiuterà a raggiungere nuovi sostenitori indispensabili per <strong>garantire un futuro ai giovani che hanno affrontato esperienze di malattia grave</strong>.\\""}'),
(1, 'textBlock', 5, '{"title":"Restituire valore alla società attraverso la comunicazione", "text":"Per A-Tono ETS, questo progetto è molto più di una campagna: è un modo per restituire valore alla società, mettendo <strong>creatività, competenza e tecnologia al servizio di chi costruisce futuro e speranza</strong>.\n\\"Siamo onorati di affiancare Fondazione Il Bullone in questa sfida,\\" racconta Anastasia Granata, presidente di A-Tono ETS. \\"Il Bullone non è solo un giornale, ma un vero laboratorio di rinascita. Il nostro obiettivo è stato tradurre la potenza emotiva di queste storie in una campagna digital efficace, capace di generare un impatto tangibile sulla vita dei B.Livers.\\""}'),
(1, 'imageGallery3', 6, '{"images":["img/progetto-2.png", "img/progetto-3.png", "img/progetto-4.png"]}');
